/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/account/': RouteRecordInfo<'/account/', '/account', Record<never, never>, Record<never, never>>,
    '/account/orders': RouteRecordInfo<'/account/orders', '/account/orders', Record<never, never>, Record<never, never>>,
    '/account/settings': RouteRecordInfo<'/account/settings', '/account/settings', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/cart': RouteRecordInfo<'/cart', '/cart', Record<never, never>, Record<never, never>>,
    '/legal/cgv': RouteRecordInfo<'/legal/cgv', '/legal/cgv', Record<never, never>, Record<never, never>>,
    '/legal/mentions-legales': RouteRecordInfo<'/legal/mentions-legales', '/legal/mentions-legales', Record<never, never>, Record<never, never>>,
    '/legal/politique-confidentialite': RouteRecordInfo<'/legal/politique-confidentialite', '/legal/politique-confidentialite', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/order/collect': RouteRecordInfo<'/order/collect', '/order/collect', Record<never, never>, Record<never, never>>,
    '/order/confirmation': RouteRecordInfo<'/order/confirmation', '/order/confirmation', Record<never, never>, Record<never, never>>,
    '/order/informations': RouteRecordInfo<'/order/informations', '/order/informations', Record<never, never>, Record<never, never>>,
    '/order/payment': RouteRecordInfo<'/order/payment', '/order/payment', Record<never, never>, Record<never, never>>,
    '/order/summary': RouteRecordInfo<'/order/summary', '/order/summary', Record<never, never>, Record<never, never>>,
    '/pastries/': RouteRecordInfo<'/pastries/', '/pastries', Record<never, never>, Record<never, never>>,
    '/pastries/[slug]': RouteRecordInfo<'/pastries/[slug]', '/pastries/:slug', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
  }
}
