services:
  server:
    image: node:23.8.0-alpine
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    working_dir: /app
    command: >
      sh -c "
        npm install &&
        npx prisma generate &&
        echo 'Waiting for MongoDB to be ready...' &&
        while ! nc -z mongo 27017; do sleep 1; done &&
        npx prisma db push &&
        npx prisma db seed &&
        exec npm run dev
      "
    ports:
      - "3333:3000"
    networks:
      - prisma-network
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb-data:/data/db
      - ./mongo/data:/home/data
    working_dir: /home/data
    networks:
      - prisma-network
    restart: unless-stopped

  mongo-express:
    image: mongo-express:1.0.2
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${DATABASE_URL}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "8081:8081"
    networks:
      - prisma-network
    depends_on:
      - mongo
    restart: unless-stopped

  prisma-studio:
    image: node:23.8.0-alpine
    working_dir: /app
    stop_grace_period: 1s
    volumes:
      - ./:/app
    command: npx prisma studio --port 5555 --browser none
    ports:
      - "5555:5555"
    env_file:
      - .env
    networks:
      - prisma-network
    depends_on:
      - server
    restart: unless-stopped

volumes:
  mongodb-data:
  node_modules:

networks:
  prisma-network:
    name: prisma-network
